version: 2.1
orbs:
    node: circleci/node@4.0.0

jobs:
    build:
        executor:
            name: node/default
        steps:
            - checkout
            - node/install-packages:
                  pkg-manager: yarn
                  override-ci-command: yarn install --immutable
            - run: yarn build

    test:
        parameters:
            node-version:
                type: string
        executor:
            name: node/default
        steps:
            - checkout
            - node/install:
                  node-version: << parameters.node-version >>
                  install-yarn: false
                  install-npm: false
            - node/install-packages:
                  pkg-manager: yarn
                  override-ci-command: yarn install --immutable
            - run: yarn test --ci --runInBand --coverage
            - store_test_results:
                  path: test-results/junit
            - store_artifacts:
                  path: test-results/junit
            - store_artifacts:
                  path: test-results/coverage

workflows:
    build-and-test:
        jobs:
            - build
            - test:
                  matrix:
                      parameters:
                          node-version:
                              - 14.9.0
                              - 12.18.3
                              - 10.22.0
